import pygame

pygame.init()

# Constants for everything
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 675
CX = SCREEN_WIDTH / 2
CY = SCREEN_HEIGHT / 2

SCREEN_AREA = SCREEN_WIDTH * SCREEN_HEIGHT

TICK_SPEED = 120

CHARCOAL = (44, 47, 51)
CYAN = (114, 137, 218)
WHITE = (255, 255, 255)

FONT = 'ariel'
MAINMENU = 'DESKTOP GAMES'
QUIT = 'Quit'

BUTTON_COLOR = CYAN
BUTTON_TEXT_COLOR = CHARCOAL

# constants representing each game
COMINGSOON = "COMING SOON"
TEMPLATEGAME = "Template Game"
SNAKEGAME = "Snake Game"
FEEDINGFRENZY = "Feeding Frenzy"

