import pygame
from Constants import *

pygame.init()

# constants for individual game start Screens
RESTART_SCREEN_WIDTH = SCREEN_WIDTH / 1.5
RESTART_SCREEN_HEIGHT = SCREEN_HEIGHT / 2
RESTART_SCREEN_POS = (CX - RESTART_SCREEN_WIDTH / 2, CY - RESTART_SCREEN_HEIGHT / 2, RESTART_SCREEN_WIDTH, RESTART_SCREEN_HEIGHT)

GAMENAME_TEXT_SIZE = SCREEN_AREA / 8000
GAMENAME_TEXT_FONT = pygame.font.SysFont(FONT, int(GAMENAME_TEXT_SIZE))
GAMENAME_TEXT_COLOR = WHITE
GAMENAME_TEXT_CENTER = (CX, SCREEN_HEIGHT * 3 / 8)

BUTTON_WIDTH = SCREEN_WIDTH / 5
BUTTON_HEIGHT = SCREEN_HEIGHT / 8
BUTTON_TEXT_SIZE = BUTTON_WIDTH / 6

BUTTON_FONT = pygame.font.SysFont(FONT, int(BUTTON_TEXT_SIZE))

PB_NAME = "Play Game"
PB_CX = SCREEN_WIDTH / 2 - BUTTON_WIDTH / 1.5
PB_CY = SCREEN_HEIGHT * 5 / 8
PB_LX = PB_CX - BUTTON_WIDTH / 2
PB_RX = PB_CX + BUTTON_WIDTH / 2
PB_LY = PB_CY - BUTTON_HEIGHT / 2
PB_RY = PB_CY + BUTTON_HEIGHT / 2

MM_NAME = "Main Menu"
MM_CX = SCREEN_WIDTH / 2 + BUTTON_WIDTH / 1.5
MM_CY = SCREEN_HEIGHT * 5 / 8
MM_LX = MM_CX - BUTTON_WIDTH / 2
MM_RX = MM_CX + BUTTON_WIDTH / 2
MM_LY = MM_CY - BUTTON_HEIGHT / 2
MM_RY = MM_CY + BUTTON_HEIGHT / 2