import pygame
from Constants import *

pygame.init()

BUTTON_WIDTH = SCREEN_WIDTH / 5
BUTTON_HEIGHT = SCREEN_HEIGHT / 8

BUTTON_TEXT_SIZE = BUTTON_WIDTH / 6
BUTTON_SPACING = BUTTON_WIDTH / 5

BUTTON_FONT = pygame.font.SysFont(FONT, int(BUTTON_TEXT_SIZE))

BUTTON_WIDTH_SPACE = BUTTON_WIDTH + BUTTON_SPACING
BUTTON_HEIGHT_SPACE = BUTTON_HEIGHT + BUTTON_SPACING

B1_NAME = FEEDINGFRENZY
B1_CX = BUTTON_WIDTH * 1 / 2 + BUTTON_SPACING
B1_CY = BUTTON_HEIGHT * 1 / 2 + BUTTON_SPACING
B1_LX = B1_CX - BUTTON_WIDTH / 2
B1_RX = B1_CX + BUTTON_WIDTH / 2
B1_LY = B1_CY - BUTTON_HEIGHT / 2
B1_RY = B1_CY + BUTTON_HEIGHT / 2

B2_NAME = "EXAMPLE GAME"
B2_CX = B1_CX + BUTTON_WIDTH_SPACE
B2_CY = B1_CY
B2_LX = B2_CX - BUTTON_WIDTH / 2
B2_RX = B2_CX + BUTTON_WIDTH / 2
B2_LY = B2_CY - BUTTON_HEIGHT / 2
B2_RY = B2_CY + BUTTON_HEIGHT / 2

B3_NAME = "EXAMPLE GAME"
B3_CX = B2_CX + BUTTON_WIDTH_SPACE
B3_CY = B2_CY
B3_LX = B3_CX - BUTTON_WIDTH / 2
B3_RX = B3_CX + BUTTON_WIDTH / 2
B3_LY = B3_CY - BUTTON_HEIGHT / 2
B3_RY = B3_CY + BUTTON_HEIGHT / 2

B4_NAME = "EXAMPLE GAME"
B4_CX = B3_CX + BUTTON_WIDTH_SPACE
B4_CY = B1_CY
B4_LX = B4_CX - BUTTON_WIDTH / 2
B4_RX = B4_CX + BUTTON_WIDTH / 2
B4_LY = B4_CY - BUTTON_HEIGHT / 2
B4_RY = B4_CY + BUTTON_HEIGHT / 2