import pygame
from Constants import *

pygame.init()

GAME_BUTTONS_PER_ROW = 4

GAME_BUTTON_WIDTH = SCREEN_WIDTH / (GAME_BUTTONS_PER_ROW + 1)
GAME_BUTTON_HEIGHT = SCREEN_HEIGHT / 8

GAME_BUTTON_TEXT_SIZE = GAME_BUTTON_WIDTH / (GAME_BUTTONS_PER_ROW * 1.5)
GAME_BUTTON_SPACING = GAME_BUTTON_WIDTH / (GAME_BUTTONS_PER_ROW + 1)

GAME_BUTTON_FONT = pygame.font.SysFont(FONT, int(GAME_BUTTON_TEXT_SIZE))

GAME_BUTTON_WIDTH_SPACE = GAME_BUTTON_WIDTH + GAME_BUTTON_SPACING
GAME_BUTTON_HEIGHT_SPACE = GAME_BUTTON_HEIGHT + GAME_BUTTON_SPACING

GAME_BASE_CX = GAME_BUTTON_WIDTH * 1 / 2 + GAME_BUTTON_SPACING
GAME_BASE_CY = GAME_BUTTON_HEIGHT * 1 / 2 + GAME_BUTTON_SPACING