name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.DESKTOP_GAMES_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

  build:
    needs: release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile -n main-${{ matrix.os}} src/main.py
      env:
        DISPLAY: ':99.0'  # For Ubuntu
    
    - name: Set asset path and name
      id: set_asset
      run: |
        echo "OS_NAME=${{ matrix.os }}"
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          echo "::set-output name=asset_path::./dist/main-${{ matrix.os }}.exe"
          echo "::set-output name=asset_name::main-${{ matrix.os }}.exe"
        else
          echo "::set-output name=asset_path::./dist/main-${{ matrix.os }}"
          echo "::set-output name=asset_name::main-${{ matrix.os }}"
        fi
      
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.DESKTOP_GAMES_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ${{ steps.set_asset.outputs.asset_path }}
        asset_name: ${{ steps.set_asset.outputs.asset_name }}
        asset_content_type: application/octet-stream
      
