name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile src/main.py
      env:
        DISPLAY: ':99.0'  # For Ubuntu

    - name: Archive the build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: dist/
        retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts
        path: ./dist

    - name: List dist directory contents (Debug)
      run: ls -la ./dist

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.DESKTOP_GAMES_TOKEN }}
        GITHUB_RELEASE: ${{ steps.create_release.outputs.upload_url }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    
    - name: Upload Release Asset (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        gh release upload ${{ github.ref }} ./dist/main --clobber
      env:
        GH_TOKEN: ${{ secrets.DESKTOP_GAMES_TOKEN }}
      
    - name: Upload Release Asset (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        gh release upload ${{ github.ref }} ./dist/main --clobber
      env:
        GH_TOKEN: ${{ secrets.DESKTOP_GAMES_TOKEN }}
      
    - name: Upload Release Asset (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        gh release upload ${{ github.ref }} ./dist/main.exe --clobber
      env:
        GH_TOKEN: ${{ secrets.DESKTOP_GAMES_TOKEN }}
      
